"""
ETL Job 4a: Export resort conditions as a static GeoJSON file.

Joins resort geometry with latest condition scores and outputs
a GeoJSON FeatureCollection that the frontend can load directly
via ArcGIS GeoJSONLayer.

Run from backend/: python etl/export_geojson.py
"""

import os
import json
import psycopg2
from datetime import date, datetime

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "dbname": os.getenv("DB_NAME", "snowview_db"),
    "user": os.getenv("DB_USER", "snowview"),
    "password": os.getenv("DB_PASSWORD", ""),
}

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "output")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "resort_conditions.geojson")


def json_serial(obj):
    """JSON serializer for types not serializable by default."""
    if isinstance(obj, (date, datetime)):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")


def export_geojson():
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    cur.execute("""
        SELECT
            r.id,
            r.name,
            r.state,
            r.base_elevation_ft,
            r.summit_elevation_ft,
            r.num_lifts,
            r.website_url,
            ST_X(r.geom) AS lng,
            ST_Y(r.geom) AS lat,
            c.computed_date,
            c.current_snow_depth_in,
            c.snowfall_48h_in,
            c.snowfall_7d_in,
            c.swe_in,
            c.snowpack_trend,
            c.forecast_snowfall_72h_in,
            c.temp_avg_f,
            c.condition_score,
            c.score_explanation,
            c.updated_at
        FROM resorts r
        LEFT JOIN resort_conditions c ON c.resort_id = r.id
            AND c.computed_date = (
                SELECT MAX(computed_date)
                FROM resort_conditions
                WHERE resort_id = r.id
            )
        ORDER BY r.state, r.name
    """)

    features = []
    for row in cur.fetchall():
        feature = {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [row[7], row[8]]  # [lng, lat]
            },
            "properties": {
                "id": row[0],
                "name": row[1],
                "state": row[2],
                "base_elevation_ft": row[3],
                "summit_elevation_ft": row[4],
                "num_lifts": row[5],
                "website_url": row[6],
                "computed_date": row[9],
                "current_snow_depth_in": row[10],
                "snowfall_48h_in": row[11],
                "snowfall_7d_in": row[12],
                "swe_in": row[13],
                "snowpack_trend": row[14],
                "forecast_snowfall_72h_in": row[15],
                "temp_avg_f": row[16],
                "condition_score": row[17],
                "score_explanation": row[18],
                "updated_at": row[19],
            }
        }
        features.append(feature)

    geojson = {
        "type": "FeatureCollection",
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "resort_count": len(features),
            "description": "SnowView resort conditions — generated by ETL pipeline"
        },
        "features": features
    }

    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(OUTPUT_FILE, "w") as f:
        json.dump(geojson, f, indent=2, default=json_serial)

    print(f"SnowView ETL — GeoJSON Export")
    print(f"{'='*60}")
    print(f"Exported {len(features)} resorts to {OUTPUT_FILE}")

    # Print a summary
    scored = [f for f in features if f["properties"]["condition_score"] is not None]
    if scored:
        scores = [f["properties"]["condition_score"] for f in scored]
        best = max(scored, key=lambda f: f["properties"]["condition_score"])
        print(f"Resorts with scores: {len(scored)}")
        print(f"Score range: {min(scores)} — {max(scores)}")
        print(f"Best conditions: {best['properties']['name']} ({best['properties']['condition_score']}/100)")

    cur.close()
    conn.close()


if __name__ == "__main__":
    export_geojson()
